/**
 * Deterministic tokens.css generator. TS tokens are the single source of
 * truth; this module renders them to CSS custom properties. The output is
 * byte-stable: keys are sorted, numbers stringified canonically, no
 * timestamps — same input, same bytes (unit-tested).
 */
import { colors } from "./colors.js";
import { elevation } from "./elevation.js";
import { breakpoints } from "./breakpoints.js";
import { radii } from "./radii.js";
import { spacing } from "./spacing.js";
import { fontFamily, fontSize, fontWeight } from "./typography.js";

const PREFIX = "--stapel";

function kebab(name: string): string {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function sortedEntries<T>(record: Record<string, T>): [string, T][] {
  return Object.entries(record).sort(([a], [b]) => (a < b ? -1 : 1));
}

function px(value: number): string {
  return value === 0 ? "0" : `${String(value)}px`;
}

/** `cssVar("color-primary")` → `var(--stapel-color-primary)` */
export function cssVar(name: string): string {
  return `var(${PREFIX}-${name})`;
}

/** Render the full tokens stylesheet (`:root` + `[data-theme="dark"]`). */
export function generateTokensCss(): string {
  const root: string[] = [];
  const dark: string[] = [];

  for (const [name, pair] of sortedEntries(colors)) {
    root.push(`${PREFIX}-color-${kebab(name)}: ${pair.light};`);
    dark.push(`${PREFIX}-color-${kebab(name)}: ${pair.dark};`);
  }
  for (const [name, pair] of sortedEntries(elevation)) {
    root.push(`${PREFIX}-elevation-${kebab(name)}: ${pair.light};`);
    dark.push(`${PREFIX}-elevation-${kebab(name)}: ${pair.dark};`);
  }
  for (const [name, value] of sortedEntries(fontFamily)) {
    root.push(`${PREFIX}-font-family-${kebab(name)}: ${value};`);
  }
  for (const [name, step] of sortedEntries(fontSize)) {
    root.push(`${PREFIX}-font-size-${kebab(name)}: ${px(step.fontSize)};`);
    root.push(`${PREFIX}-line-height-${kebab(name)}: ${px(step.lineHeight)};`);
  }
  for (const [name, value] of sortedEntries(fontWeight)) {
    root.push(`${PREFIX}-font-weight-${kebab(name)}: ${String(value)};`);
  }
  for (const [name, value] of sortedEntries(spacing)) {
    root.push(`${PREFIX}-space-${kebab(name)}: ${px(value)};`);
  }
  for (const [name, value] of sortedEntries(radii)) {
    root.push(`${PREFIX}-radius-${kebab(name)}: ${px(value)};`);
  }
  for (const [name, value] of sortedEntries(breakpoints)) {
    root.push(`${PREFIX}-breakpoint-${kebab(name)}: ${px(value)};`);
  }

  const indent = (lines: string[]): string =>
    lines.map((l) => `  ${l}`).join("\n");

  return [
    "/* Generated by @stapel/tokens — do not edit. Source: src/*.ts */",
    ":root {",
    indent(root),
    "}",
    "",
    '[data-theme="dark"] {',
    indent(dark),
    "}",
    "",
  ].join("\n");
}
