/**
 * The pair's error map (frontend-standard §4 checklist #7): the generated
 * `code → { status, params, remediation, en }` catalog plus a lookup helper.
 *
 * It is generated from stapel-docs' OWN registry — the same 77 codes
 * `@stapel/docs-react` carries, because the drive surfaces are that module's
 * endpoints. Shipping it here rather than borrowing the peer's is deliberate:
 * `registerDriveI18n(engine)` has to make a drive screen fully translatable
 * on its own, and a host that mounts the drive product without also calling
 * `registerDocsI18n` would otherwise watch every backend refusal render as
 * its raw code. Bytes for an invariant.
 *
 * Generated by `pnpm gen:errors` against the pinned v0.5.0 contract and
 * drift-gated by `pnpm gen:errors:check`.
 */
import { DRIVE_ERRORS } from "./generated/errors.gen.js";
import type { Remediation } from "./generated/errors.gen.js";

export {
  DRIVE_ERRORS,
  DRIVE_ERROR_CODES,
  driveErrorBundleEn,
} from "./generated/errors.gen.js";
export type {
  DriveErrorCode,
  DriveErrorSpec,
  Remediation,
} from "./generated/errors.gen.js";

/**
 * Resolve a backend error code to its remediation hint, or `undefined` for a
 * code this module does not know (a cross-cutting `stapel.http.*` fallback,
 * or one of the pair's own client-side keys — `drive.error.unknown` is not a
 * backend code and deliberately has no entry).
 */
export function explainDriveError(code: string): Remediation | undefined {
  return (DRIVE_ERRORS as Record<string, { remediation: Remediation }>)[code]
    ?.remediation;
}
