import type { StapelClient, StapelRequestOptions } from "@stapel/core";
import {
  exportDocument,
  getDocumentContent,
  getRevisionContent,
  getSharedContent,
  putDocumentContent,
  uploadToPutUrl,
} from "./content.js";
import type { DocsRawTransport, PutContentOptions } from "./content.js";
import type {
  AppendResult,
  CreateDocumentRequest,
  CreateFolderRequest,
  CreateRevisionRequest,
  CreateLinkRequest,
  CreateUploadRequest,
  CreateUploadResponse,
  DocDocument,
  DocFolder,
  DocRevision,
  DocUpdatesResponse,
  DocumentAccessGrant,
  DocumentContent,
  DocumentListParams,
  DocumentShareLink,
  DownloadUrl,
  EmptyTrashRequest,
  GrantAccessRequest,
  PatchDocumentRequest,
  PatchFolderRequest,
  PostUpdateRequest,
  SaveContentResult,
  SharedDocument,
  TrashListing,
  TrashPurgeResult,
} from "./types.js";

/**
 * CSRF rule for cookie-authenticated browser clients (mirrors the other
 * pairs): always send `X-Requested-With: XMLHttpRequest` on mutating
 * requests. Header-token clients ignore it; it is harmless there. stapel-docs
 * authenticates like every stapel module (the `stapel_jwt` cookie), so a
 * browser host on a cross-origin API builds its runtime with
 * `credentials: "include"`.
 */
const CSRF_HEADERS: Record<string, string> = {
  "X-Requested-With": "XMLHttpRequest",
};

function mutating(
  options?: Omit<StapelRequestOptions, "method" | "body">
): Omit<StapelRequestOptions, "method" | "body"> {
  return {
    ...options,
    headers: { ...CSRF_HEADERS, ...options?.headers },
  };
}

/** Optional raw-transport knobs `createDocsRuntime` forwards (see content.ts). */
export interface DocsApiOptions {
  readonly fetch?: typeof globalThis.fetch;
  readonly credentials?: RequestCredentials;
  readonly defaultHeaders?: Record<string, string>;
}

/**
 * The pair's typed operation surface — one method per stapel-docs endpoint a
 * JS client may call, bound to the injected {@link StapelClient} (the
 * per-module override seam of frontend-standard §7.2). Paths are relative to
 * the runtime's `baseUrl` (e.g. `/docs/api/v1/`). List routes require the
 * workspace scope; object routes authorize server-side by id.
 *
 * These operations are hand-authored here — the ONE legal home of path
 * strings (`stapel/no-string-paths` §2.3 carve-out) — but every SHAPE they
 * carry is an alias of the generated schema (`api/types.ts` → `api/generated/
 * schema.ts`, regenerated by `pnpm gen:api` from the backend's own
 * `docs/schema.json` and drift-gated). The raw-bytes surface (content /
 * export / revision content / presigned upload PUT) lives in
 * `api/content.ts` and is re-exposed here so hooks reach everything through
 * `useDocsApi()`.
 */
export interface DocsApi {
  readonly client: StapelClient;

  // ── folders ────────────────────────────────────────────────────────────────
  listFolders(workspaceId: string): Promise<DocFolder[]>;
  createFolder(body: CreateFolderRequest): Promise<DocFolder>;
  getFolder(folderId: string): Promise<DocFolder>;
  patchFolder(folderId: string, body: PatchFolderRequest): Promise<DocFolder>;
  /** Move the folder to the trash. */
  deleteFolder(folderId: string): Promise<void>;
  restoreFolder(folderId: string): Promise<DocFolder>;

  // ── documents ──────────────────────────────────────────────────────────────
  listDocuments(params: DocumentListParams): Promise<DocDocument[]>;
  createDocument(body: CreateDocumentRequest): Promise<DocDocument>;
  getDocument(documentId: string): Promise<DocDocument>;
  patchDocument(
    documentId: string,
    body: PatchDocumentRequest
  ): Promise<DocDocument>;
  /** Move the document to the trash. */
  deleteDocument(documentId: string): Promise<void>;
  restoreDocument(documentId: string): Promise<DocDocument>;

  // ── content (raw bytes; see api/content.ts) ────────────────────────────────
  getContent(documentId: string, signal?: AbortSignal): Promise<DocumentContent>;
  putContent(
    documentId: string,
    body: BodyInit,
    options: PutContentOptions
  ): Promise<SaveContentResult>;
  /** `GET /documents/:id/download` — an opaque URL to hand to the browser. */
  getDownloadUrl(documentId: string): Promise<DownloadUrl>;
  exportDocument(
    documentId: string,
    format: string,
    signal?: AbortSignal
  ): Promise<Blob>;

  // ── updates (crdt-discipline types only — every v1 builtin is snapshot) ───
  /** Replay the journal from `since` — or the resync order when `since` fell
   * out of the retained window (`isUpdatesResync`). */
  getUpdates(documentId: string, since?: number): Promise<DocUpdatesResponse>;
  /** Append a BATCH of opaque encoded updates; answers the new head. */
  postUpdate(documentId: string, body: PostUpdateRequest): Promise<AppendResult>;

  // ── revisions ──────────────────────────────────────────────────────────────
  listRevisions(documentId: string): Promise<DocRevision[]>;
  createRevision(
    documentId: string,
    body: CreateRevisionRequest
  ): Promise<DocRevision>;
  getRevisionContent(
    documentId: string,
    revisionId: string,
    signal?: AbortSignal
  ): Promise<Blob>;
  getRevisionDownloadUrl(
    documentId: string,
    revisionId: string
  ): Promise<DownloadUrl>;
  /** Restore the document's content to this revision (lands as a new head). */
  restoreRevision(documentId: string, revisionId: string): Promise<DocDocument>;

  // ── trash ──────────────────────────────────────────────────────────────────
  listTrash(workspaceId: string): Promise<TrashListing>;
  /** Answers how many folders / documents were irreversibly purged. */
  emptyTrash(body: EmptyTrashRequest): Promise<TrashPurgeResult>;

  // ── sharing (0.6: whitelist grants, bearer links, the bearer's own read) ──
  /**
   * `GET /documents/:id/access` — who has been granted this document.
   *
   * Gated server-side on `docs.share.whitelist`: the listing names OTHER
   * PEOPLE, so seeing it is itself a sharing-administration act rather than a
   * document read, and a caller without the capability gets a 403 — which is
   * the honest signal a share sheet reads to decide whether to offer the
   * people section at all.
   */
  listAccess(documentId: string): Promise<DocumentAccessGrant[]>;
  /** `POST /documents/:id/access` — grant, or re-grant at a new level
   * (upsert: re-granting is the sheet's ordinary gesture, not an error). */
  grantAccess(
    documentId: string,
    body: GrantAccessRequest
  ): Promise<DocumentAccessGrant>;
  /** `DELETE /documents/:id/access/:accessId` — revoke one grant. */
  revokeAccess(documentId: string, accessId: string): Promise<void>;
  /**
   * `GET /documents/:id/links` — the bearer links minted for this document,
   * TOKENS INCLUDED. Gated on `docs.share.link` for exactly that reason.
   */
  listLinks(documentId: string): Promise<DocumentShareLink[]>;
  /** `POST /documents/:id/links` — mint one. The level is capped by the
   * deployment's `SHARING.LINK.MAX_LEVEL`; above it the backend REFUSES
   * (`error.400.docs_share_level`) rather than silently clamping. */
  createLink(
    documentId: string,
    body?: CreateLinkRequest
  ): Promise<DocumentShareLink>;
  /** `DELETE /documents/:id/links/:linkId` — revoke one link. Terminal: a
   * revoked link never revives. */
  revokeLink(documentId: string, linkId: string): Promise<void>;
  /** `GET /shared/:token` — the bearer's stripped view of the document. */
  getSharedDocument(token: string): Promise<SharedDocument>;
  /** `GET /shared/:token/content` — the bearer's read of the body (bytes). */
  getSharedContent(token: string, signal?: AbortSignal): Promise<DocumentContent>;
  /** `GET /shared/:token/download` — an opaque presigned URL for the bearer. */
  getSharedDownloadUrl(token: string): Promise<DownloadUrl>;

  // ── uploads ────────────────────────────────────────────────────────────────
  createUpload(body: CreateUploadRequest): Promise<CreateUploadResponse>;
  finalizeUpload(uploadId: string): Promise<DocDocument>;
  /** Step 2 of the presigned path — raw PUT at `put_url` (object store). */
  uploadToPutUrl(
    putUrl: string,
    blob: Blob,
    options?: { readonly contentType?: string; readonly signal?: AbortSignal }
  ): Promise<Response>;
}

export function createDocsApi(
  client: StapelClient,
  options?: DocsApiOptions
): DocsApi {
  const transport: DocsRawTransport = {
    baseUrl: client.baseUrl,
    ...(options?.fetch !== undefined ? { fetch: options.fetch } : {}),
    ...(options?.credentials !== undefined
      ? { credentials: options.credentials }
      : {}),
    ...(options?.defaultHeaders !== undefined
      ? { headers: options.defaultHeaders }
      : {}),
  };

  const folderPath = (folderId: string): string =>
    `/folders/${encodeURIComponent(folderId)}`;
  const documentPath = (documentId: string): string =>
    `/documents/${encodeURIComponent(documentId)}`;
  const sharedPath = (token: string): string =>
    `/shared/${encodeURIComponent(token)}`;

  return {
    client,

    // folders
    listFolders: (workspaceId) =>
      client.get("/folders", { query: { workspace_id: workspaceId } }),
    createFolder: (body) => client.post("/folders", body, mutating()),
    getFolder: (folderId) => client.get(folderPath(folderId)),
    patchFolder: (folderId, body) =>
      client.patch(folderPath(folderId), body, mutating()),
    deleteFolder: (folderId) => client.delete(folderPath(folderId), mutating()),
    restoreFolder: (folderId) =>
      client.post(`${folderPath(folderId)}/restore`, {}, mutating()),

    // documents
    listDocuments: (params) =>
      client.get("/documents", {
        query: {
          workspace_id: params.workspaceId,
          folder_id: params.folderId,
          type: params.type,
          q: params.q,
        },
      }),
    createDocument: (body) => client.post("/documents", body, mutating()),
    getDocument: (documentId) => client.get(documentPath(documentId)),
    patchDocument: (documentId, body) =>
      client.patch(documentPath(documentId), body, mutating()),
    deleteDocument: (documentId) =>
      client.delete(documentPath(documentId), mutating()),
    restoreDocument: (documentId) =>
      client.post(`${documentPath(documentId)}/restore`, {}, mutating()),

    // content
    getContent: (documentId, signal) =>
      getDocumentContent(transport, documentId, signal),
    putContent: (documentId, body, putOptions) =>
      putDocumentContent(transport, documentId, body, putOptions),
    getDownloadUrl: (documentId) =>
      client.get(`${documentPath(documentId)}/download`),
    exportDocument: (documentId, format, signal) =>
      exportDocument(transport, documentId, format, signal),

    // updates
    getUpdates: (documentId, since) =>
      client.get(`${documentPath(documentId)}/updates`, {
        query: { since },
      }),
    postUpdate: (documentId, body) =>
      client.post(`${documentPath(documentId)}/updates`, body, mutating()),

    // revisions
    listRevisions: (documentId) =>
      client.get(`${documentPath(documentId)}/revisions`),
    createRevision: (documentId, body) =>
      client.post(`${documentPath(documentId)}/revisions`, body, mutating()),
    getRevisionContent: (documentId, revisionId, signal) =>
      getRevisionContent(transport, documentId, revisionId, signal),
    getRevisionDownloadUrl: (documentId, revisionId) =>
      client.get(
        `${documentPath(documentId)}/revisions/${encodeURIComponent(revisionId)}/download`
      ),
    restoreRevision: (documentId, revisionId) =>
      client.post(
        `${documentPath(documentId)}/revisions/${encodeURIComponent(revisionId)}/restore`,
        {},
        mutating()
      ),

    // trash
    listTrash: (workspaceId) =>
      client.get("/trash", { query: { workspace_id: workspaceId } }),
    emptyTrash: (body) => client.post("/trash/empty", body, mutating()),

    // sharing
    listAccess: (documentId) => client.get(`${documentPath(documentId)}/access`),
    grantAccess: (documentId, body) =>
      client.post(`${documentPath(documentId)}/access`, body, mutating()),
    revokeAccess: (documentId, accessId) =>
      client.delete(
        `${documentPath(documentId)}/access/${encodeURIComponent(accessId)}`,
        mutating()
      ),
    listLinks: (documentId) => client.get(`${documentPath(documentId)}/links`),
    createLink: (documentId, body) =>
      client.post(`${documentPath(documentId)}/links`, body ?? {}, mutating()),
    revokeLink: (documentId, linkId) =>
      client.delete(
        `${documentPath(documentId)}/links/${encodeURIComponent(linkId)}`,
        mutating()
      ),
    getSharedDocument: (token) => client.get(sharedPath(token)),
    getSharedContent: (token, signal) =>
      getSharedContent(transport, token, signal),
    getSharedDownloadUrl: (token) => client.get(`${sharedPath(token)}/download`),

    // uploads
    createUpload: (body) => client.post("/uploads", body, mutating()),
    finalizeUpload: (uploadId) =>
      client.post(
        `/uploads/${encodeURIComponent(uploadId)}/finalize`,
        {},
        mutating()
      ),
    uploadToPutUrl: (putUrl, blob, uploadOptions) =>
      uploadToPutUrl(putUrl, blob, uploadOptions),
  };
}
