import { afterAll, afterEach, beforeAll, describe, expect, it, vi } from "vitest";
import { http, HttpResponse } from "msw";
import { setupServer } from "msw/node";
import { AUTH_FLOWS, flowEndpoints } from "../src/flows/generated/flows.gen.js";
import type { AuthFlowId } from "../src/flows/generated/flows.gen.js";
import { createOtpFlow } from "../src/flows/otpFlow.js";
import { createPasswordLoginFlow } from "../src/flows/passwordLoginFlow.js";
import { createVerificationController } from "../src/flows/verificationFlow.js";
import { BASE, makeApi, authResponse } from "./helpers.js";

/**
 * The flow CONTRACT test — the teeth of the flows.json → machine scaffold
 * (docs/flow-system.md §5). It proves the drift gate is not cosmetic: the
 * covered machines bind their analytics id AND their HTTP surface to the
 * generated registry, so a backend flow rename / re-endpoint (regenerated by
 * `pnpm gen:flows`) breaks these assertions rather than silently skewing the
 * analytics funnel or the client contract.
 */

const server = setupServer();
beforeAll(() => server.listen({ onUnhandledRequest: "error" }));
afterEach(() => {
  server.resetHandlers();
  server.events.removeAllListeners();
});
afterAll(() => server.close());

/** flows.json paths carry `<str:challenge_id>` placeholders; match any segment. */
function pathMatcher(registryPath: string): RegExp {
  const escaped = registryPath
    .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    .replace(/<[^>]+>/g, "[^/]+");
  return new RegExp(`^${escaped}$`);
}

function declaresPath(id: AuthFlowId, pathname: string): boolean {
  return flowEndpoints(id).some((e) => pathMatcher(e.path).test(pathname));
}

describe("flow registry integrity", () => {
  it("every entry's key equals its canonical id and carries well-formed i18n keys", () => {
    for (const [key, spec] of Object.entries(AUTH_FLOWS)) {
      expect(spec.id).toBe(key);
      expect(spec.titleKey).toBe(`flow.${spec.id}.title`);
      expect(spec.descriptionKey).toBe(`flow.${spec.id}.description`);
      // Steps are ordered.
      const orders = spec.steps.map((s) => s.order);
      expect(orders).toEqual([...orders].sort((a, b) => a - b));
    }
  });
});

describe("machine ↔ registry id binding (analytics funnel = documented flow)", () => {
  function spyAnalytics(): { track: ReturnType<typeof vi.fn>; analytics: never } {
    const track = vi.fn();
    return {
      track,
      analytics: {
        track,
        identify: vi.fn(),
        page: vi.fn(),
        flush: vi.fn(),
        setConsent: vi.fn(),
        getConsent: () => "granted" as const,
        register: vi.fn(),
        unregister: vi.fn(),
      } as never,
    };
  }

  it("otp (passwordless) flow emits flow.auth.passwordless_login.*", async () => {
    server.use(
      http.post(`${BASE}/email/request/`, () =>
        HttpResponse.json({ message: "sent", target: "a***@b.com" })
      )
    );
    const { track, analytics } = spyAnalytics();
    const flow = createOtpFlow({ api: makeApi(), analytics });
    await flow.requestCode("email", "a@b.com");
    const ids = track.mock.calls.map((c) => c[0] as string);
    expect(ids.every((n) => n.startsWith(`flow.${AUTH_FLOWS["auth.passwordless_login"].id}.`))).toBe(true);
  });

  it("password login flow emits flow.auth.password_login.*", async () => {
    server.use(
      http.post(`${BASE}/password/login/`, () => HttpResponse.json(authResponse()))
    );
    const { track, analytics } = spyAnalytics();
    const flow = createPasswordLoginFlow({ api: makeApi(), analytics });
    await flow.login("ada", "pw");
    const ids = track.mock.calls.map((c) => c[0] as string);
    expect(ids.every((n) => n.startsWith(`flow.${AUTH_FLOWS["auth.password_login"].id}.`))).toBe(true);
  });
});

describe("machine HTTP surface ⊆ registry endpoints (no undeclared path drift)", () => {
  /** Record every request path so it can be checked against the flow contract. */
  function recorder(): string[] {
    const seen: string[] = [];
    server.events.on("request:start", ({ request }) => {
      seen.push(new URL(request.url).pathname);
    });
    return seen;
  }

  it("password login happy path (login + TOTP branch) only hits declared endpoints", async () => {
    const seen = recorder();
    server.use(
      http.post(`${BASE}/password/login/`, () =>
        HttpResponse.json({
          status: "TOTP_REQUIRED",
          challenge_token: "ct_1",
          expires_in: 300,
        })
      ),
      http.post(`${BASE}/totp/challenge/verify/`, () =>
        HttpResponse.json(authResponse())
      )
    );
    const flow = createPasswordLoginFlow({ api: makeApi() });
    await flow.login("ada", "pw");
    await flow.submitTotp({ code: "123456" });
    expect(flow.machine.getState().step).toBe("authenticated");

    const apiPaths = seen.filter((p) => p.startsWith("/auth/api/"));
    expect(apiPaths.length).toBeGreaterThan(0);
    for (const p of apiPaths) {
      expect(declaresPath("auth.password_login", p)).toBe(true);
    }
  });

  it("step-up verification write path (initiate + complete) is declared", async () => {
    const seen = recorder();
    server.use(
      http.post(`${BASE}/verification/chg_1/initiate/`, () =>
        HttpResponse.json({ factor: "otp_email", data: { target: "a***@b.com" } })
      ),
      http.post(`${BASE}/verification/chg_1/complete/`, () =>
        HttpResponse.json({ verified: true, verification_token: "vt_1" })
      )
    );
    const controller = createVerificationController({ api: makeApi() });
    // Drive the controller by feeding it a challenge as core would.
    const outcome = controller.handler({
      challenge_id: "chg_1",
      scope: "payout",
      factors: ["otp_email"],
      expires_at: Math.floor(Date.now() / 1000) + 300,
    } as never);
    await controller.chooseFactor("otp_email");
    await controller.submitCode({ code: "1234" });
    await outcome;

    const apiPaths = seen.filter((p) => p.startsWith("/auth/api/"));
    expect(apiPaths.length).toBeGreaterThan(0);
    for (const p of apiPaths) {
      expect(declaresPath("auth.step_up_verification", p)).toBe(true);
    }
  });
});
