#!/usr/bin/env node
// AUTO-GEN driver for a pair's backend error map (frontend-core-architecture
// §2.5, §4c). Emits the machine-facing projection of the backend module's error
// registry: every `error.<status>.<code>` key it can raise, its `{param}`
// interpolation slots, an English fallback, and its declared remediation.
//
// WHY: a `StapelApiError.code` is already an i18n key, but if the pair ships no
// en fallback for it the host renders the RAW KEY (review found 43 stapel-auth
// keys — qr_*, oauth_failed, email_taken, refresh_invalid, … — with no
// fallback). Generating the bundle from the registry makes coverage total by
// construction, and the drift gate (`pnpm gen:errors:check`) turns a NEW backend
// key into a red diff instead of a silent raw key at runtime.
//
// SOURCE: the backend's CANONICAL codegen artifact `errors.json` — emitted by
// stapel-auth alongside schema.json/flows.json (task `error-remediation`) and
// committed at `stapel-auth/docs/errors.json`. It is a byte-stable JSON array of
// `{ code, status, params, remediation, en }`, already sorted by `code`, and is
// the SUPERSET of every key the pair can surface (auth registry + cross-cutting
// stapel-core verification + captcha/network/common/field families). This driver
// no longer parses Python sources or re-derives remediation/en heuristically:
// the backend now declares all of it, so we consume the artifact verbatim.
//
//   AUTH_ERRORS_JSON     backend errors.json path        (default ../stapel-auth/docs/errors.json)
//   ERRORS_OUT           output dir                      (default packages/auth-react/src/i18n/generated)
//   ERRORS_CONST         registry const name             (default "AUTH_ERRORS")
//   ERRORS_TYPE_PREFIX   generated type-name prefix      (default "Auth")
//
//   node scripts/gen-errors.mjs        # generate
//   pnpm gen:errors                    # generate (root script)
//   pnpm gen:errors:check              # drift gate (fails on divergence)
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const SOURCE = resolve(
  ROOT,
  process.env.AUTH_ERRORS_JSON ?? "../stapel-auth/docs/errors.json"
);
const OUT_DIR =
  process.env.ERRORS_OUT ??
  resolve(ROOT, "packages/auth-react/src/i18n/generated");
const CONST = process.env.ERRORS_CONST ?? "AUTH_ERRORS";
const TYPE_PREFIX = process.env.ERRORS_TYPE_PREFIX ?? "Auth";

const OUT_TS = resolve(OUT_DIR, "errors.gen.ts");
const OUT_JSON = resolve(OUT_DIR, "errors.json");

const HEADER = `// AUTO-GENERATED by scripts/gen-errors.mjs — do not edit by hand.
// Source: stapel-auth canonical errors.json (backend codegen artifact).
// Regenerate: pnpm gen:errors   ·   Drift gate: pnpm gen:errors:check
`;

// The remediation vocabulary is declared by the backend; we assert every
// consumed value stays within the finite set the host UX branches on so a new
// backend value can't slip in unnoticed.
const REMEDIATIONS = new Set([
  "retry",
  "wait_and_retry",
  "reauthenticate",
  "verify",
  "fix_input",
  "contact_support",
  "bug",
]);

/** Extract `{name}` interpolation slots, de-duplicated, in first-seen order. */
function paramsOf(en) {
  const seen = [];
  for (const m of en.matchAll(/\{(\w+)\}/g)) {
    if (!seen.includes(m[1])) seen.push(m[1]);
  }
  return seen;
}

function normalize(raw) {
  if (!Array.isArray(raw))
    throw new Error(`errors.json must be a JSON array, got ${typeof raw}`);
  const entries = raw.map((e) => {
    if (!e || typeof e.code !== "string" || typeof e.en !== "string")
      throw new Error(`bad error entry: ${JSON.stringify(e)}`);
    if (!REMEDIATIONS.has(e.remediation))
      throw new Error(
        `error ${e.code}: unknown remediation "${e.remediation}" (expected one of ${[...REMEDIATIONS].join(", ")})`
      );
    const params = Array.isArray(e.params) ? e.params : paramsOf(e.en);
    return {
      code: e.code,
      status: Number(e.status ?? Number.parseInt(e.code.split(".")[1], 10)),
      params,
      remediation: e.remediation,
      en: e.en,
    };
  });
  // Stable order = sort by code, so regeneration is byte-identical (the backend
  // artifact is already sorted, but we don't rely on it).
  return entries.sort((a, b) => a.code.localeCompare(b.code));
}

async function main() {
  const raw = JSON.parse(await readFile(SOURCE, "utf8"));
  const entries = normalize(raw);
  if (entries.length === 0)
    throw new Error(`no error keys in ${SOURCE}`);

  const specLines = entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.code)}: { status: ${e.status}, params: ${JSON.stringify(
          e.params
        )}, remediation: ${JSON.stringify(e.remediation)}, en: ${JSON.stringify(e.en)} },`
    )
    .join("\n");

  const bundleLines = entries
    .map((e) => `  ${JSON.stringify(e.code)}: ${JSON.stringify(e.en)},`)
    .join("\n");

  const codesLines = entries
    .map((e) => `  ${JSON.stringify(e.code)},`)
    .join("\n");

  const body = `${HEADER}
/**
 * Remediation vocabulary (frontend-core-architecture §2.5). Declared by the
 * backend on the error registry and consumed verbatim from its \`errors.json\`
 * artifact. A host maps it to UX — retryable → "try again"; \`wait_and_retry\` →
 * timer from \`params.retry_after_minutes\`; \`verify\` → the step-up seam;
 * \`fix_input\` → highlight the offending field.
 */
export type Remediation =
  | "retry"
  | "wait_and_retry"
  | "reauthenticate"
  | "verify"
  | "fix_input"
  | "contact_support"
  | "bug";

export interface ${TYPE_PREFIX}ErrorSpec {
  /** HTTP status the backend raises this key with. */
  readonly status: number;
  /** \`{param}\` interpolation slots present in the message. */
  readonly params: readonly string[];
  /** Remediation hint declared by the backend (see {@link Remediation}). */
  readonly remediation: Remediation;
  /** English fallback (source: stapel-auth errors.json). */
  readonly en: string;
}

/**
 * The ${CONST} map — every \`error.*\` key stapel-auth can raise, keyed by its
 * canonical code. The single source of truth behind the en fallback bundle, the
 * remediation lookup, and the manifest \`errors\` block.
 */
export const ${CONST} = {
${specLines}
} as const;

export type ${TYPE_PREFIX}ErrorCode = keyof typeof ${CONST};

/** Every backend error code this module can surface, sorted. */
export const ${TYPE_PREFIX.toUpperCase()}_ERROR_CODES: readonly ${TYPE_PREFIX}ErrorCode[] = [
${codesLines}
];

/**
 * English fallback bundle — one string per backend key, so a \`StapelApiError.code\`
 * never renders as a raw key. Merged UNDER the hand-polished UI copy in
 * {@link authI18nBundleEn} (polish wins; this guarantees coverage).
 */
export const ${TYPE_PREFIX.toLowerCase()}ErrorBundleEn: Record<${TYPE_PREFIX}ErrorCode, string> = {
${bundleLines}
};
`;

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_TS, body);
  await writeFile(
    OUT_JSON,
    `${JSON.stringify(
      entries.map((e) => ({
        code: e.code,
        status: e.status,
        params: e.params,
        remediation: e.remediation,
        en: e.en,
      })),
      null,
      2
    )}\n`
  );

  console.error(
    `gen:errors: ${entries.length} error keys from ${SOURCE}\n            → ${OUT_TS}`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
