#!/usr/bin/env node
// AUTO-GEN driver for a pair's backend error map (frontend-core-architecture
// §2.5, §4c). Emits the machine-facing projection of the backend module's error
// registry: every `error.<status>.<code>` key it can raise, its `{param}`
// interpolation slots, an English fallback, and a provisional remediation hint.
//
// WHY: a `StapelApiError.code` is already an i18n key, but if the pair ships no
// en fallback for it the host renders the RAW KEY (review found 43 stapel-auth
// keys — qr_*, oauth_failed, email_taken, refresh_invalid, … — with no
// fallback). Generating the bundle from the registry makes coverage total by
// construction, and the drift gate (`pnpm gen:errors:check`) turns a NEW backend
// key into a red diff instead of a silent raw key at runtime.
//
// SOURCE: the backend registries the pair surfaces — the module's own
// `errors.py` (`AUTH_ERRORS` dict, same map `register_service_errors` feeds the
// runtime `/error-keys/` view) PLUS the cross-cutting `stapel_core.verification`
// registry (the step-up flow the auth pair implements raises those keys —
// frontend-standard §2). Each is a `KEY: 'en',` dict with `ERR_* = 'error.*'`
// constants (constants may live in a sibling file: verification defines them in
// grants.py, the en dict in errors.py — we scan every listed file for both).
// Parsed as *files*, hermetic + byte-stable (mirrors gen-api/gen-flows). The
// proper long-term source is a codegen artifact (`errors.json`) emitted by the
// backend alongside schema.json/flows.json — a backend follow-up (task
// `error-remediation`); until then we read the module sources directly.
//
//   AUTH_ERRORS_SOURCES  comma-separated source files    (default: auth + verification registries)
//   ERRORS_OUT           output dir                      (default packages/auth-react/src/i18n/generated)
//   ERRORS_CONST         registry const name             (default "AUTH_ERRORS")
//   ERRORS_TYPE_PREFIX   generated type-name prefix      (default "Auth")
//
//   node scripts/gen-errors.mjs        # generate
//   pnpm gen:errors                    # generate (root script)
//   pnpm gen:errors:check              # drift gate (fails on divergence)
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const DEFAULT_SOURCES = [
  "../stapel-auth/errors.py",
  "../stapel-core/verification/grants.py",
  "../stapel-core/verification/errors.py",
];
const SOURCES = (
  process.env.AUTH_ERRORS_SOURCES
    ? process.env.AUTH_ERRORS_SOURCES.split(",")
    : DEFAULT_SOURCES
).map((p) => resolve(ROOT, p.trim()));
const OUT_DIR =
  process.env.ERRORS_OUT ??
  resolve(ROOT, "packages/auth-react/src/i18n/generated");
const CONST = process.env.ERRORS_CONST ?? "AUTH_ERRORS";
const TYPE_PREFIX = process.env.ERRORS_TYPE_PREFIX ?? "Auth";

const OUT_TS = resolve(OUT_DIR, "errors.gen.ts");
const OUT_JSON = resolve(OUT_DIR, "errors.json");

const HEADER = `// AUTO-GENERATED by scripts/gen-errors.mjs — do not edit by hand.
// Source: stapel-auth errors.py (AUTH_ERRORS registry).
// Regenerate: pnpm gen:errors   ·   Drift gate: pnpm gen:errors:check
`;

/** Python string-literal unescape (single/double quoted, one line). */
function unescape(raw) {
  return raw.replace(/\\(['"\\])/g, "$1");
}

/** Extract `{name}` interpolation slots, de-duplicated, in first-seen order. */
function paramsOf(en) {
  const seen = [];
  for (const m of en.matchAll(/\{(\w+)\}/g)) {
    if (!seen.includes(m[1])) seen.push(m[1]);
  }
  return seen;
}

/**
 * Provisional remediation hint (frontend-core-architecture §2.5 finite set:
 * retry | wait_and_retry | reauthenticate | verify | fix_input |
 * contact_support | bug). HEURISTIC until the backend declares it as part of
 * the error registry (task `error-remediation`). Keyed off status + name.
 */
function remediationOf(code, status, params) {
  const name = code.split(".").slice(2).join(".");
  if (/verification|step_up|enrollment/.test(name)) return "verify";
  if (params.some((p) => p.startsWith("retry_after")) || [422, 423, 429].includes(status))
    return "wait_and_retry";
  if (/sso_required/.test(name)) return "reauthenticate";
  if (status === 401) return "reauthenticate";
  if (status === 500) return "contact_support";
  if (status === 409) return "fix_input";
  if (status === 404)
    return /not_found/.test(name) ? "retry" : "fix_input";
  if (status === 403) return "retry";
  if (status === 400)
    return /expired|challenge|not_pending|qr_(expired|fulfilled|not_found)|magic_link_invalid|code_required/.test(
      name
    )
      ? "retry"
      : "fix_input";
  return "retry";
}

function parse(src) {
  // Pass 1: ERR_* = 'error.<status>.<code>' constant defs (across all sources —
  // e.g. verification defines its constants in grants.py, the en dict elsewhere).
  const constToCode = new Map();
  for (const m of src.matchAll(/^(ERR_\w+)\s*=\s*["']([^"']+)["']/gm)) {
    if (m[2].startsWith("error.")) constToCode.set(m[1], m[2]);
  }
  // Pass 2: any error-dict entry — `ERR_*: '<en>',` — in any listed registry.
  const byCode = new Map();
  for (const m of src.matchAll(
    /^\s*(ERR_\w+):\s*(['"])((?:\\.|(?!\2).)*)\2\s*,?\s*(?:#.*)?$/gm
  )) {
    const code = constToCode.get(m[1]);
    if (!code) continue; // not an error key
    if (byCode.has(code)) continue; // first registration wins (stable)
    const en = unescape(m[3]);
    const status = Number.parseInt(code.split(".")[1], 10);
    byCode.set(code, {
      code,
      status,
      params: paramsOf(en),
      remediation: remediationOf(code, status, paramsOf(en)),
      en,
    });
  }
  // Stable order = sort by code, so regeneration is byte-identical.
  return [...byCode.values()].sort((a, b) => a.code.localeCompare(b.code));
}

async function main() {
  const parts = [];
  for (const file of SOURCES) parts.push(await readFile(file, "utf8"));
  const entries = parse(parts.join("\n"));
  if (entries.length === 0)
    throw new Error(`no error keys parsed from ${SOURCES.join(", ")}`);

  const specLines = entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.code)}: { status: ${e.status}, params: ${JSON.stringify(
          e.params
        )}, remediation: ${JSON.stringify(e.remediation)}, en: ${JSON.stringify(e.en)} },`
    )
    .join("\n");

  const bundleLines = entries
    .map((e) => `  ${JSON.stringify(e.code)}: ${JSON.stringify(e.en)},`)
    .join("\n");

  const codesLines = entries
    .map((e) => `  ${JSON.stringify(e.code)},`)
    .join("\n");

  const body = `${HEADER}
/**
 * Remediation vocabulary (frontend-core-architecture §2.5). PROVISIONAL: derived
 * heuristically from status + key name until the backend declares it on the
 * error registry (task \`error-remediation\`). A host maps it to UX — retryable →
 * "try again"; \`wait_and_retry\` → timer from \`params.retry_after_minutes\`;
 * \`verify\` → the step-up seam; \`fix_input\` → highlight the offending field.
 */
export type Remediation =
  | "retry"
  | "wait_and_retry"
  | "reauthenticate"
  | "verify"
  | "fix_input"
  | "contact_support"
  | "bug";

export interface ${TYPE_PREFIX}ErrorSpec {
  /** HTTP status the backend raises this key with. */
  readonly status: number;
  /** \`{param}\` interpolation slots present in the message. */
  readonly params: readonly string[];
  /** Provisional remediation hint (see {@link Remediation}). */
  readonly remediation: Remediation;
  /** English fallback (source: stapel-auth errors.py). */
  readonly en: string;
}

/**
 * The ${CONST} map — every \`error.*\` key stapel-auth can raise, keyed by its
 * canonical code. The single source of truth behind the en fallback bundle, the
 * remediation lookup, and the manifest \`errors\` block.
 */
export const ${CONST} = {
${specLines}
} as const;

export type ${TYPE_PREFIX}ErrorCode = keyof typeof ${CONST};

/** Every backend error code this module can surface, sorted. */
export const ${TYPE_PREFIX.toUpperCase()}_ERROR_CODES: readonly ${TYPE_PREFIX}ErrorCode[] = [
${codesLines}
];

/**
 * English fallback bundle — one string per backend key, so a \`StapelApiError.code\`
 * never renders as a raw key. Merged UNDER the hand-polished UI copy in
 * {@link authI18nBundleEn} (polish wins; this guarantees coverage).
 */
export const ${TYPE_PREFIX.toLowerCase()}ErrorBundleEn: Record<${TYPE_PREFIX}ErrorCode, string> = {
${bundleLines}
};
`;

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_TS, body);
  await writeFile(
    OUT_JSON,
    `${JSON.stringify(
      entries.map((e) => ({
        code: e.code,
        status: e.status,
        params: e.params,
        remediation: e.remediation,
        en: e.en,
      })),
      null,
      2
    )}\n`
  );

  console.error(
    `gen:errors: ${entries.length} error keys from ${SOURCES.length} source(s)\n            → ${OUT_TS}`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
