#!/usr/bin/env node
// AUTO-GEN driver for the typed flow registry (docs/flow-system.md §5).
//
// Reads the language-agnostic `flows.json` emitted by the all-modules codegen
// source (stapel-example-monolith `make codegen` → `generate_flow_docs`) and
// scaffolds a typed, frozen flow registry consumed by the auth-react flow
// machines. This is the machine-facing projection of the single flow source:
// the SAME flows.json also renders the SA-doc (people) and the Gherkin `.feature`
// (E2E). `createFlowMachine` bodies stay hand-written; what the codegen owns is
// the CONTRACT each machine binds to — its canonical id, i18n keys, and the
// ordered step→endpoint map — so a backend flow change surfaces here as a drift.
//
// Source: a *file*, hermetic + byte-stable for the drift gate (mirrors
// gen-api.mjs). The live monolith serves the identical document for the dev
// loop. Point elsewhere with FLOWS_JSON=/path/to/flows.json.
//
//   node scripts/gen-flows.mjs         # generate
//   pnpm gen:flows                     # generate (root script)
//   pnpm gen:flows:check               # drift gate (fails on divergence)
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

const FLOWS_PATH =
  process.env.FLOWS_JSON ??
  resolve(ROOT, "../stapel-example-monolith/codegen/generated/flows.json");

const OUT_DIR = resolve(ROOT, "packages/auth-react/src/flows/generated");
const OUT_JSON = resolve(OUT_DIR, "flows.json");
const OUT_TS = resolve(OUT_DIR, "flows.gen.ts");

const HEADER = `// AUTO-GENERATED by scripts/gen-flows.mjs — do not edit by hand.
// Source: unified Stapel flows.json (stapel-example-monolith \`make codegen\`).
// Regenerate: pnpm gen:flows   ·   Drift gate: pnpm gen:flows:check
`;

/** Stable key ordering so regeneration is byte-identical. */
function stableFlow(flow) {
  return {
    id: flow.id,
    titleKey: flow.title_key,
    descriptionKey: flow.description_key,
    actors: [...(flow.actors ?? [])],
    steps: (flow.steps ?? []).map((s) => ({
      kind: s.kind,
      order: s.order,
      noteKey: s.note_key,
      ref: s.ref ?? "",
      endpoints: (s.endpoints ?? []).map((e) => ({
        method: e.method,
        path: e.path,
      })),
    })),
  };
}

function lit(value) {
  // Deterministic TS literal — 2-space indent, sorted by source order.
  return JSON.stringify(value, null, 2);
}

async function main() {
  const raw = await readFile(FLOWS_PATH, "utf8");
  const flows = JSON.parse(raw);
  if (!Array.isArray(flows)) {
    throw new Error(`flows.json is not an array: ${FLOWS_PATH}`);
  }
  const stable = flows.map(stableFlow).sort((a, b) => a.id.localeCompare(b.id));

  const entries = stable
    .map((f) => `  ${JSON.stringify(f.id)}: ${lit(f).replace(/\n/g, "\n  ")},`)
    .join("\n");

  const body = `${HEADER}
/**
 * The canonical auth flow registry — the machine-facing projection of the flow
 * source (docs/flow-system.md §5). Each entry carries a flow's canonical id
 * (\`flow.<id>.<step>\` analytics funnel = this flow), its i18n keys, and its
 * ordered step→endpoint contract. Flow machines bind their \`id\` to
 * \`AUTH_FLOWS[...].id\` so a backend flow rename/re-step surfaces as a drift
 * here (\`pnpm gen:flows:check\`) rather than a silent analytics/contract skew.
 */
export const AUTH_FLOWS = {
${entries}
} as const;

/** Canonical flow ids present in flows.json (a subset grows as the backend annotates more). */
export type AuthFlowId = keyof typeof AUTH_FLOWS;

export type AuthFlowSpec = (typeof AUTH_FLOWS)[AuthFlowId];

export interface FlowEndpoint {
  readonly method: string;
  readonly path: string;
}

/** All HTTP endpoints a flow touches, in step order (for the contract test / MSW). */
export function flowEndpoints(id: AuthFlowId): readonly FlowEndpoint[] {
  return AUTH_FLOWS[id].steps.flatMap(
    (s) => s.endpoints as readonly FlowEndpoint[]
  );
}
`;

  await mkdir(OUT_DIR, { recursive: true });
  await writeFile(OUT_JSON, `${JSON.stringify(stable, null, 2)}\n`);
  await writeFile(OUT_TS, body);

  console.error(
    `gen:flows: ${stable.length} flows from ${FLOWS_PATH}\n           → ${OUT_TS}`
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
