#!/usr/bin/env node
// AUTO-GEN driver for the Stapel typed API surface (docs/flow-system.md §0.1).
//
// Reads a single backend module's committed OpenAPI schema.json and generates a
// types-only TypeScript module (`components`/`paths`/`operations`) consumed by
// that module's `@stapel/<module>-react` pair.
//
// §17-native per-module contract: each pair generates its OWN self-contained
// schema from its backend's committed `docs/schema.json` — there is no unified
// monolith aggregate any more, and @stapel/core no longer carries a shared
// schema export (nothing consumed it; core has no DRF surface of its own). The
// monolith is retired as a contract source (contract-pipeline.md §5).
//
// Generator choice: openapi-typescript — types only, zero runtime. It pairs
// with @stapel/core's own fetch client (no bundled client/hooks runtime like
// orval), so it adds nothing to the package's shipped bytes.
//
// Source: a *file*, not an HTTP endpoint — hermetic + byte-stable for the drift
// gate.
//
//   API_SCHEMA   source schema.json  (REQUIRED, e.g. ../stapel-auth/docs/schema.json)
//   API_OUT      output schema.ts    (REQUIRED, e.g. packages/auth-react/src/api/generated/schema.ts)
//
//   API_SCHEMA=… API_OUT=… node scripts/gen-api.mjs   # generate one pair
//   pnpm gen:api                                        # generate all pairs (root script)
//   pnpm gen:api:check                                  # drift gate (fails on divergence)
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// Both knobs are required — every consumer is a per-module pair with its own
// source + destination. There is no monolith default any more.
if (!process.env.API_SCHEMA || !process.env.API_OUT) {
  console.error(
    "gen:api: API_SCHEMA and API_OUT are both required (per-module contract).\n" +
      "  e.g. API_SCHEMA=../stapel-auth/docs/schema.json \\\n" +
      "       API_OUT=packages/auth-react/src/api/generated/schema.ts node scripts/gen-api.mjs",
  );
  process.exit(1);
}

const SCHEMA_PATH = resolve(ROOT, process.env.API_SCHEMA);
const OUT_PATH = resolve(ROOT, process.env.API_OUT);

const HEADER = `// AUTO-GENERATED by scripts/gen-api.mjs — do not edit by hand.
// Source: the backend module's own docs/schema.json (§17-native per-module contract).
// Regenerate: pnpm gen:api   ·   Drift gate: pnpm gen:api:check
`;

async function main() {
  const raw = await readFile(SCHEMA_PATH, "utf8");
  const schema = JSON.parse(raw);
  const pathCount = Object.keys(schema.paths ?? {}).length;

  const ast = await openapiTS(schema);
  const body = astToString(ast);

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, HEADER + body);

  console.error(
    `gen:api: ${pathCount} paths from ${SCHEMA_PATH}\n         → ${OUT_PATH}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
