#!/usr/bin/env node
// AUTO-GEN driver for the Stapel typed API surface (docs/flow-system.md §0.1).
//
// Reads the unified OpenAPI schema.json emitted by the all-modules codegen
// source (stapel-example-monolith `make codegen`) and generates a types-only
// TypeScript module consumed by @stapel/core and its per-lib consumers.
//
// Generator choice: openapi-typescript — types only, zero runtime. It pairs
// with @stapel/core's own fetch client (no bundled client/hooks runtime like
// orval), so it adds nothing to the package's shipped bytes.
//
// Source: a *file*, not an HTTP endpoint — hermetic + byte-stable for the drift
// gate. The live monolith still serves the identical document at /schema/ for
// the dev loop. Point elsewhere with API_SCHEMA=/path/to/schema.json.
//
// OUTPUT (§17-native per-module contract): a pair whose backend is NOT in the
// unified monolith schema (it emits its OWN docs/schema.json — see
// stapel-calendar) generates a package-LOCAL schema module instead of relying on
// core's shared `components`. Point the output with API_OUT=packages/<pkg>/src/
// api/generated/schema.ts and the source with API_SCHEMA=../<backend>/docs/
// schema.json — the same env-knob shape as gen-errors' ERRORS_OUT. The default
// (unset) stays the core-owned shared schema, so existing pairs are unchanged.
//
//   API_SCHEMA   source schema.json  (default sibling monolith)
//   API_OUT      output schema.ts    (default packages/core/src/generated/schema.ts)
//
//   node scripts/gen-api.mjs           # generate
//   pnpm gen:api                       # generate (root script)
//   pnpm gen:api:check                 # drift gate (fails on divergence)
import { readFile, writeFile, mkdir } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");

// Default: the sibling monolith's committed schema.json in the workspace.
const SCHEMA_PATH =
  process.env.API_SCHEMA ??
  resolve(ROOT, "../stapel-example-monolith/codegen/generated/schema.json");

const OUT_PATH = resolve(
  ROOT,
  process.env.API_OUT ?? "packages/core/src/generated/schema.ts"
);

// The default output is the core-owned unified schema; a per-module contract
// (API_SCHEMA + API_OUT) is generated from its own backend docs/schema.json.
const IS_MODULE_LOCAL = Boolean(process.env.API_OUT);
const HEADER = `// AUTO-GENERATED by scripts/gen-api.mjs — do not edit by hand.
// Source: ${
  IS_MODULE_LOCAL
    ? "the backend module's own docs/schema.json (§17-native per-module contract)."
    : "unified Stapel OpenAPI (stapel-example-monolith `make codegen`)."
}
// Regenerate: pnpm gen:api   ·   Drift gate: pnpm gen:api:check
`;

async function main() {
  const raw = await readFile(SCHEMA_PATH, "utf8");
  const schema = JSON.parse(raw);
  const pathCount = Object.keys(schema.paths ?? {}).length;

  const ast = await openapiTS(schema);
  const body = astToString(ast);

  await mkdir(dirname(OUT_PATH), { recursive: true });
  await writeFile(OUT_PATH, HEADER + body);

  console.error(
    `gen:api: ${pathCount} paths from ${SCHEMA_PATH}\n         → ${OUT_PATH}`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
