/**
 * THE DISC A PERSON WITH NO PHOTOGRAPH GETS: their initials on a tint that is
 * always the same tint for the same person.
 *
 * ── Why it lives in the bridge and not in a pair ──────────────────────────
 *
 * Four surfaces draw a person on this fleet — a result card's seller line, the
 * seller page, the listing page's seller block and the chat inbox — and they
 * are drawn by TWO packages: `@stapel/profiles-react`'s `<PersonAvatar>` and
 * `@stapel/chat-react`'s `<CounterpartyAvatar>`. Neither may import the other.
 * A tint decided inside one of them is the same person wearing two different
 * colours on one screen, which is worse than the flat grey both had.
 *
 * So the decision lives once, here, in the package both already depend on and
 * the one whose whole job is stating design decisions in antd's vocabulary.
 *
 * ── The tint is DERIVED, never assigned ───────────────────────────────────
 *
 * From a stable key the caller owns — a user id, and a display name only when
 * there is no id — through a fixed hash. Never from render order, never from
 * an index in a list, never from anything random: a face that changes colour
 * when a list re-sorts is not an identity, and two lists showing the same
 * person would disagree.
 *
 * ── The colours are the design system's own, and they are a PAIR ──────────
 *
 * The families are antd's preset palettes, which are part of the design
 * system's vocabulary and are regenerated by the active algorithm — so a dark
 * page gets the dark palette without this module knowing which page it is on.
 * No hex is written here.
 *
 * The disc is the family's shade {@link IDENTITY_TINT_DISC_SHADE} and the
 * initials are shade {@link IDENTITY_TINT_INK_SHADE} OF THE SAME FAMILY, and
 * the two are returned TOGETHER by one function on purpose. A caller that
 * could take the background from here and the text colour from somewhere else
 * is a caller that can pair a measured operand with an assumed one — which is
 * the exact shape of a contrast claim that passes a gate and fails on screen.
 * There is one way to get a tint and it hands over both halves.
 *
 * ── The numbers, measured across every family in both algorithms ──────────
 *
 * Initials against their own disc, worst case of 13 families × 2 algorithms:
 *
 *   disc 1 / ink  8   3.19:1   fails
 *   disc 2 / ink  8   3.13:1   fails
 *   disc 2 / ink  9   5.05:1   passes
 *   disc 2 / ink 10   8.40:1   passes   ← this one
 *   disc 6 / ink  1   1.36:1   fails
 *
 * 8.40:1 is light/yellow; every other family clears 9.3:1, and the dark
 * algorithm's worst is 10.3:1. The bar is 4.5:1 and no family is dropped to
 * clear it — the set is all thirteen.
 *
 * The saturated construction every product reaches for first (a shade-6 disc
 * with light initials) is in that table because it was measured and REFUSED:
 * the preset families differ enormously in luminance at shade 6 — yellow is
 * nearly white there and purple is nearly black — so no single ink shade
 * clears the bar across the set, and the only way to ship it would be to drop
 * families until the rest passed by accident.
 *
 * ── What this construction does NOT buy, stated rather than hidden ────────
 *
 * The DISC against the page behind it is 1.04:1 at its worst (light/yellow):
 * a pale tint on a pale ground has almost no luminance contrast, and the
 * measurement is the same 1.1:1 for every alternative shade in this vocabulary
 * because the worst family is near-white at every light shade. The identity is
 * carried by the INITIALS, which clear 8.4:1; the disc is a hue, and hue is
 * not luminance. This is no worse than the flat `colorFillQuaternary` both
 * packages drew before — that is a 4% fill, invisible by the same measure —
 * and it is strictly better for the letters on top of it. A visible boundary
 * would be a hairline in the family's own shade 4; it is not drawn here
 * because nobody asked for a ring around every face, and it is one
 * declaration if somebody does.
 */
import { theme as antdTheme } from "antd";
import type { GlobalToken } from "antd";

/**
 * The preset families an identity tint is drawn from — antd's own, in a fixed
 * order, because the order is part of what makes the answer deterministic.
 *
 * All thirteen. The set is not narrowed for contrast: see the header for the
 * measurement that says it does not need to be.
 */
export const IDENTITY_TINT_FAMILIES = [
  "blue",
  "purple",
  "cyan",
  "green",
  "magenta",
  "pink",
  "red",
  "orange",
  "yellow",
  "volcano",
  "geekblue",
  "lime",
  "gold",
] as const;

/** One of {@link IDENTITY_TINT_FAMILIES}. */
export type IdentityTintFamily = (typeof IDENTITY_TINT_FAMILIES)[number];

/** The shade the DISC is painted in. See the header's table. */
export const IDENTITY_TINT_DISC_SHADE = 2;
/** The shade the INITIALS are painted in — the same family's far end. */
export const IDENTITY_TINT_INK_SHADE = 10;

/** A disc and the ink that goes on it. Never one without the other. */
export interface IdentityTint {
  /** Which preset family, so a test and a walker can name what they see. */
  readonly family: IdentityTintFamily;
  /** The disc. */
  readonly background: string;
  /** The initials, on that disc. */
  readonly color: string;
}

/**
 * FNV-1a over the key's UTF-16 code units, as an unsigned 32-bit integer.
 *
 * Spelled out rather than taken from a dependency because it has to be STABLE:
 * the same person must get the same colour in this release and in the next
 * one, on the server and in the browser, so the arithmetic is part of the
 * contract rather than an implementation detail somebody may improve.
 *
 * `>>> 0` after the multiply keeps it in 32 bits; `Math.imul` is what makes
 * the multiply wrap the same way everywhere instead of drifting into a double.
 */
function hash32(key: string): number {
  let value = 0x811c9dc5;
  for (let index = 0; index < key.length; index += 1) {
    value ^= key.charCodeAt(index);
    value = Math.imul(value, 0x01000193) >>> 0;
  }
  return value >>> 0;
}

/**
 * Which family this key wears. Stable for the life of the key.
 *
 * An empty key is not special-cased into a "no tint" arm: it hashes like any
 * other string and lands on a family, because the alternative is one grey disc
 * for everybody a caller could not name — which is the thing this module
 * exists to replace.
 */
export function identityTintFamily(key: string): IdentityTintFamily {
  const index = hash32(key) % IDENTITY_TINT_FAMILIES.length;
  // Non-null: the modulus is bounded by the array's own length.
  return IDENTITY_TINT_FAMILIES[index] as IdentityTintFamily;
}

/**
 * The tint for a key, out of a token the CALLER has already resolved.
 *
 * The token must be the live one — `theme.useToken()` inside the skin — and
 * not a design token computed somewhere else, because the algorithm is what
 * turns these families into their dark counterparts. {@link useIdentityTint}
 * is the form that cannot get that wrong.
 */
export function identityTint(key: string, token: GlobalToken): IdentityTint {
  const family = identityTintFamily(key);
  const shade = (index: number): string =>
    // The preset scales are flat fields on the token (`blue2`, `blue10`, …).
    String((token as unknown as Record<string, unknown>)[`${family}${String(index)}`] ?? "");
  return {
    family,
    background: shade(IDENTITY_TINT_DISC_SHADE),
    color: shade(IDENTITY_TINT_INK_SHADE),
  };
}

/**
 * The tint for a key, under whatever theme the surface is standing in.
 *
 * This is the form a component should use: it reads the LIVE token, so a
 * runtime flip to the dark palette repaints the disc and its initials
 * together, out of the same algorithm, and neither half can be stale while
 * the other moved.
 */
export function useIdentityTint(key: string): IdentityTint {
  const { token } = antdTheme.useToken();
  return identityTint(key, token);
}
