import { describe, expect, it } from "vitest";
import { RECORDINGS_FLOWS } from "../src/flows/generated/flows.gen.js";

/**
 * The flow CONTRACT test (docs/flow-system.md §5): proves the flows.json →
 * registry drift gate is not cosmetic. Each registry entry's key equals its
 * canonical id and carries well-formed i18n keys with ordered steps — so a
 * backend flow rename / re-endpoint (regenerated by `pnpm gen:flows`) breaks
 * these assertions rather than silently skewing the analytics funnel or the
 * client contract. Machine ↔ registry binding + HTTP-surface assertions arrive
 * per flow as you scaffold machines from flows.json (see auth-react
 * `test/flowsContract.test.ts` for the full msw-backed pattern).
 */
describe("flow registry integrity", () => {
  it("every entry's key equals its canonical id and carries well-formed i18n keys", () => {
    for (const [key, spec] of Object.entries(RECORDINGS_FLOWS)) {
      expect(spec.id).toBe(key);
      expect(spec.titleKey).toBe(`flow.${spec.id}.title`);
      expect(spec.descriptionKey).toBe(`flow.${spec.id}.description`);
      const orders = spec.steps.map((s) => s.order);
      expect(orders).toEqual([...orders].sort((a, b) => a - b));
    }
  });
});
