// @vitest-environment node
import { execFileSync, spawnSync } from "node:child_process";
import { mkdtempSync, openAsBlob, rmSync, writeFileSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { afterAll, describe, expect, it, vi } from "vitest";
import { extractAudioTrack } from "../src/upload/index.js";

/**
 * Remux on real files (generated by test/fixtures/upload/generate.sh: H.264 +
 * AAC with a speech-like modulated tone). The ffprobe/ffmpeg assertions are
 * the proof that the output is a playable m4a carrying exactly the source's
 * audio packets; they need ffmpeg on PATH and are skipped without it.
 */
const FIX = resolve(fileURLToPath(new URL(".", import.meta.url)), "fixtures/upload");
const HAS_FFPROBE = spawnSync("ffprobe", ["-version"]).status === 0;
const tmp = mkdtempSync(join(tmpdir(), "remux-"));
afterAll(() => rmSync(tmp, { recursive: true, force: true }));

async function fixture(name: string): Promise<Blob & { name: string }> {
  const blob = await openAsBlob(join(FIX, name));
  return Object.assign(blob, { name });
}

function probe(path: string, args: string[]): string {
  return execFileSync("ffprobe", ["-v", "error", ...args, path], { encoding: "utf8" });
}

/** Every audio packet: timing, size and a hash of its bytes. */
function audioPackets(path: string): string {
  return probe(path, [
    "-select_streams", "a:0",
    "-show_packets", "-show_data_hash", "sha256",
    "-show_entries", "packet=pts,dts,duration,size,data_hash",
    "-of", "csv=p=0",
  ]);
}

function streams(path: string): Array<Record<string, string>> {
  const out = probe(path, ["-show_entries", "stream=codec_type,codec_name,duration,start_time", "-of", "json"]);
  return (JSON.parse(out) as { streams: Array<Record<string, string>> }).streams;
}

const REMUXABLE: Record<string, string> = {
  "av.mp4": "mp4a",
  "av-faststart.m4v": "mp4a",
  "av.mov": "mp4a",
  "editlist.mp4": "mp4a",
  "opus.mp4": "Opus",
};

describe("extractAudioTrack — remuxable inputs", () => {
  for (const [name, codec] of Object.entries(REMUXABLE)) {
    it(`${name} → audio-only m4a`, async () => {
      const src = await fixture(name);
      const r = await extractAudioTrack(src);
      expect(r).not.toBeNull();
      if (!r) return;
      expect(r.name).toBe(name.replace(/\.[^.]+$/, ".m4a"));
      expect(r.contentType).toBe("audio/mp4");
      expect(r.blob.type).toBe("audio/mp4");
      expect(r.codec).toBe(codec);
      expect(r.originalBytes).toBe(statSync(join(FIX, name)).size);
      expect(r.blob.size).toBeLessThan(src.size);
      expect(r.durationSeconds).toBeGreaterThan(2.9);

      if (!HAS_FFPROBE) return;
      const out = join(tmp, r.name);
      writeFileSync(out, new Uint8Array(await r.blob.arrayBuffer()));
      const [orig] = streams(join(FIX, name)).filter((s) => s.codec_type === "audio");
      const got = streams(out);
      // One stream, audio, same codec, same start and duration.
      expect(got).toHaveLength(1);
      expect(got[0]?.codec_type).toBe("audio");
      expect(got[0]?.codec_name).toBe(orig?.codec_name);
      expect(got[0]?.duration).toBe(orig?.duration);
      expect(got[0]?.start_time).toBe(orig?.start_time);
      // The reported duration is the presentation end (edit list included).
      expect(r.durationSeconds).toBeCloseTo(Number(orig?.start_time) + Number(orig?.duration), 2);
      // The very same packets, byte for byte, with the same timestamps.
      expect(audioPackets(out)).toBe(audioPackets(join(FIX, name)));
      // Only audio bytes: container overhead aside, the mdat is the packets.
      const packetBytes = audioPackets(out)
        .trim()
        .split("\n")
        .reduce((s, line) => s + Number(line.split(",")[3]), 0);
      expect(r.blob.size - packetBytes).toBeLessThan(4096);
      // It decodes cleanly end to end.
      const dec = spawnSync("ffmpeg", ["-v", "error", "-i", out, "-f", "null", "-"], { encoding: "utf8" });
      expect(dec.status).toBe(0);
      expect(dec.stderr).toBe("");
    });
  }

  it("editlist.mp4 keeps the edit list (presentation starts late)", async () => {
    const r = await extractAudioTrack(await fixture("editlist.mp4"));
    expect(r).not.toBeNull();
    // 0.5 s empty edit + 3 s of audio (minus the AAC priming the edit trims).
    expect(r?.durationSeconds).toBeGreaterThan(3.4);
  });

  it("is zero-copy: reads only box headers and the moov, audio stays slice references", async () => {
    const src = await fixture("av.mp4");
    const reads: number[] = [];
    const realSlice = src.slice.bind(src);
    vi.spyOn(src, "slice").mockImplementation((start, end, type) => {
      const part = realSlice(start, end, type);
      const realRead = part.arrayBuffer.bind(part);
      vi.spyOn(part, "arrayBuffer").mockImplementation(async () => {
        const buf = await realRead();
        reads.push(buf.byteLength);
        return buf;
      });
      return part;
    });
    const wholeRead = vi.spyOn(src, "arrayBuffer");
    const r = await extractAudioTrack(src);
    expect(r).not.toBeNull();
    expect(wholeRead).not.toHaveBeenCalled();
    // Header probes (≤16 B each) plus one moov read; the moov is small.
    const big = reads.filter((n) => n > 16);
    expect(big).toHaveLength(1);
    expect(big[0]).toBeLessThan(src.size / 4);
  });
});

describe("extractAudioTrack — falls back to null", () => {
  it("fragmented mp4", async () => {
    expect(await extractAudioTrack(await fixture("fragmented.mp4"))).toBeNull();
  });

  it("QuickTime PCM (sowt) is not an allowed sample entry", async () => {
    expect(await extractAudioTrack(await fixture("pcm.mov"))).toBeNull();
  });

  it("no audio track", async () => {
    expect(await extractAudioTrack(await fixture("video-only.mp4"))).toBeNull();
  });

  it("not ISO BMFF (WebM/EBML magic)", async () => {
    const webm = new Blob([new Uint8Array([0x1a, 0x45, 0xdf, 0xa3, 0x9f, 0x42, 0x86, 0x81, 1, 0, 0, 0, 0])]);
    expect(await extractAudioTrack(webm)).toBeNull();
  });

  it("empty and garbage inputs", async () => {
    expect(await extractAudioTrack(new Blob([]))).toBeNull();
    const junk = new Uint8Array(4096).map((_, i) => (i * 131 + 7) & 0xff);
    expect(await extractAudioTrack(new Blob([junk]))).toBeNull();
  });

  it("truncated file (moov cut off)", async () => {
    const src = await fixture("av-faststart.m4v");
    const cut = src.slice(0, 2000);
    expect(await extractAudioTrack(cut)).toBeNull();
  });

  it("unsupported sample entry (mp4a renamed to lpcm)", async () => {
    const bytes = new Uint8Array(await (await fixture("av.mp4")).arrayBuffer());
    const at = findLast(bytes, "mp4a");
    expect(at).toBeGreaterThan(0);
    bytes.set([0x6c, 0x70, 0x63, 0x6d], at);
    expect(await extractAudioTrack(new Blob([bytes]))).toBeNull();
  });

  it("stz2 sample sizes", async () => {
    const bytes = new Uint8Array(await (await fixture("av.mp4")).arrayBuffer());
    const at = findLast(bytes, "stsz");
    bytes.set([0x73, 0x74, 0x7a, 0x32], at);
    expect(await extractAudioTrack(new Blob([bytes]))).toBeNull();
  });
});

function findLast(bytes: Uint8Array, fourcc: string): number {
  const c = [...fourcc].map((ch) => ch.charCodeAt(0));
  for (let i = bytes.length - 4; i >= 0; i--) {
    if (bytes[i] === c[0] && bytes[i + 1] === c[1] && bytes[i + 2] === c[2] && bytes[i + 3] === c[3]) return i;
  }
  return -1;
}
