/**
 * The FeatureDef emitter, gated — schema in, expected TypeScript out.
 *
 * `scripts/gen-feature-def.mjs` is a hand-written emitter rather than
 * `json-schema-to-typescript` (not in this repo's node_modules, and a code
 * generator is a heavy dependency for one 200-line canon). The architecture
 * spec allows that on ONE condition: a test that holds the emitted text
 * against an expected one, so "narrow and deterministic" is a measurement and
 * not a claim.
 *
 * The fixture below exercises every construct the canon uses — a `$defs`
 * object honouring `required`, an INLINE object (all-optional, open), an
 * `enum`, a `const`, an array of `$ref`, a nullable union, a closed object
 * (`additionalProperties: false`, so no index signature) — plus the one thing
 * the canon does not: an unsupported `type`, which must THROW rather than emit
 * a silently wrong `unknown`.
 *
 * It runs the driver as a process, the way `pnpm gen:feature-def` does, so
 * what is measured is the contract (env in, file out) and not an internal.
 */
// @vitest-environment node
import { execFileSync } from "node:child_process";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

const PKG_DIR = resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
const REPO_ROOT = resolve(PKG_DIR, "../..");
const DRIVER = resolve(REPO_ROOT, "scripts/gen-feature-def.mjs");

const FIXTURE = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  title: "Sample",
  description: "A tiny canon covering every construct the emitter supports.",
  $defs: {
    Thing: {
      type: "object",
      required: ["slug", "config"],
      properties: {
        slug: { type: "string", minLength: 1, description: "Payload key." },
        config: {
          type: "object",
          required: ["type"],
          properties: { type: { type: "string" } },
        },
        id: { type: ["integer", "string", "null"] },
        mode: { enum: ["a", "b"], default: "a" },
        parts: { type: "array", default: [], items: { $ref: "#/$defs/Part" } },
        note: { type: ["string", "null"] },
        payload: { description: "Any JSON." },
      },
    },
    Part: {
      type: "object",
      required: ["kind"],
      additionalProperties: false,
      properties: {
        kind: { const: "part" },
        size: { type: "number" },
      },
    },
  },
};

function emit(schema: unknown): string {
  const dir = mkdtempSync(join(tmpdir(), "gen-feature-def-"));
  const schemaPath = join(dir, "schema.json");
  const outPath = join(dir, "out.ts");
  writeFileSync(schemaPath, JSON.stringify(schema));
  execFileSync(process.execPath, [DRIVER], {
    cwd: REPO_ROOT,
    env: { ...process.env, FEATURE_DEF_SCHEMA: schemaPath, FEATURE_DEF_OUT: outPath },
    stdio: "pipe",
  });
  return readFileSync(outPath, "utf8");
}

describe("scripts/gen-feature-def.mjs", () => {
  const emitted = emit(FIXTURE);

  it("emits exactly the expected module", () => {
    expect(emitted).toBe(`// AUTO-GENERATED by scripts/gen-feature-def.mjs — do not edit by hand.
// Source: stapel-attributes docs/feature-def.schema.json (§68 canon of a FeatureDef).
// Regenerate: pnpm gen:feature-def   ·   Drift gate: pnpm gen:feature-def:check
//
// A tiny canon covering every construct the emitter supports.

export interface ThingConfig {
  readonly type?: string;
  /** The wire carries more than the canon describes. */
  readonly [key: string]: unknown;
}

export interface Thing {
  /** Payload key. */
  readonly slug: string;
  readonly config: ThingConfig;
  readonly id?: number | string | null;
  /** @default "a" */
  readonly mode?: "a" | "b";
  /** @default [] */
  readonly parts?: readonly Part[];
  readonly note?: string | null;
  /** Any JSON. */
  readonly payload?: unknown;
  /** The wire carries more than the canon describes. */
  readonly [key: string]: unknown;
}

export interface Part {
  readonly kind: "part";
  readonly size?: number;
}
`);
  });

  it("refuses a construct it cannot emit, instead of guessing", () => {
    // A silently wrong `unknown` is worse than a red generator: it compiles,
    // ships, and the field it describes is untyped for the rest of its life.
    expect(() =>
      emit({ $defs: { Bad: { type: "object", properties: { x: { type: "tuple" } } } } })
    ).toThrow();
  });
});
